const theme = require("../theme");

// Editor Groups & Tabs
// https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-groups-tabs

module.exports = {
  "editorGroup.border": theme.ash[800],
  "editorGroup.dropBackground": theme.slate,
  "editorGroup.dropIntoPromptBackground": theme.slate[400],
  "editorGroup.dropIntoPromptBorder": theme.blue,
  "editorGroup.dropIntoPromptForeground": theme.ash,
  "editorGroup.emptyBackground": theme.slate,
  "editorGroup.focusedEmptyBorder": theme.red,
  "editorGroupHeader.border": theme.ash[800],
  "editorGroupHeader.noTabsBackground": theme.slate[600],
  "editorGroupHeader.tabsBackground": theme.slate[600],
  "editorGroupHeader.tabsBorder": theme.ash[800],
  "editorPane.background": theme.slate,
  "sideBySideEditor.horizontalBorder": theme.red,
  "sideBySideEditor.verticalBorder": theme.red,
  "tab.activeBackground": theme.slate,
  "tab.activeBorder": theme.transparent,
  "tab.activeBorderTop": theme.ash[50],
  "tab.activeForeground": theme.ash,
  "tab.activeModifiedBorder": theme.blue,
  "tab.border": theme.transparent,
  "tab.dragAndDropBorder": theme.blue,
  "tab.hoverBackground": theme.slate,
  "tab.hoverBorder": theme.transparent,
  "tab.hoverForeground": theme.ash,
  "tab.inactiveBackground": theme.slate[600],
  "tab.inactiveForeground": theme.ash[700],
  "tab.inactiveModifiedBorder": theme.blue,
  "tab.lastPinnedBorder": theme.ash[800],
  "tab.selectedBackground": theme.slate,
  "tab.selectedBorderTop": theme.blue,
  "tab.selectedForeground": theme.ash,
  "tab.unfocusedActiveBackground": theme.slate[600],
  "tab.unfocusedActiveBorder": theme.transparent,
  "tab.unfocusedActiveBorderTop": theme.transparent,
  "tab.unfocusedActiveForeground": theme.ash[700],
  "tab.unfocusedActiveModifiedBorder": theme.blue,
  "tab.unfocusedHoverBackground": theme.slate,
  "tab.unfocusedHoverBorder": theme.ash[800],
  "tab.unfocusedHoverForeground": theme.ash,
  "tab.unfocusedInactiveBackground": theme.slate[600],
  "tab.unfocusedInactiveForeground": theme.ash[50],
  "tab.unfocusedInactiveModifiedBorder": theme.blue,
};
