const theme = require("../theme");

// Editor Colors
// https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors

module.exports = {
  "editor.background": theme.background,
  "editor.findMatchBackground": theme.foregroundAlpha50,
  "editor.findMatchHighlightBackground": theme.foregroundAlpha25,
  "editor.findRangeHighlightBackground": theme.foregroundAlpha25,
  "editor.foreground": theme.foreground,
  "editor.hoverHighlightBackground": theme.foregroundAlpha50,
  "editor.inactiveSelectionBackground": theme.foregroundAlpha50,
  "editor.lineHighlightBackground": theme.backgroundLight,
  "editor.lineHighlightBorder": theme.transparent,
  "editor.occurrencesHighlight": theme.backgroundLight,
  "editor.rangeHighlightBackground": theme.foregroundAlpha50,
  "editor.selectionBackground": theme.foregroundAlpha50,
  "editor.selectionHighlightBackground": theme.foregroundAlpha25,
  "editor.wordHighlightBackground": theme.transparent,
  "editor.wordHighlightStrongBackground": theme.transparent,
  "editorBracketMatch.background": theme.foregroundAlpha50,
  "editorBracketMatch.border": theme.transparent,
  "editorCodeLens.foreground": theme.foregroundDark,
  "editorCursor.foreground": theme.foreground,
  "editorError.border": theme.background,
  "editorError.foreground": theme.red,
  "editorGutter.addedBackground": theme.green,
  "editorGutter.background": theme.background,
  "editorGutter.deletedBackground": theme.red,
  "editorGutter.modifiedBackground": theme.blue,
  "editorIndentGuide.activeBackground": theme.foregroundDark,
  "editorIndentGuide.background": theme.backgroundLight,
  "editorLineNumber.activeForeground": theme.foregroundDark,
  "editorLineNumber.foreground": theme.foregroundDark,
  "editorLink.activeForeground": theme.blue,
  "editorOverviewRuler.addedForeground": theme.green,
  "editorOverviewRuler.border": theme.backgroundLight,
  "editorOverviewRuler.deletedForeground": theme.red,
  "editorOverviewRuler.errorForeground": theme.red,
  "editorOverviewRuler.findMatchForeground": theme.foregroundAlpha25,
  "editorOverviewRuler.infoForeground": theme.blue,
  "editorOverviewRuler.modifiedForeground": theme.blue,
  "editorOverviewRuler.rangeHighlightForeground": theme.yellow,
  "editorOverviewRuler.selectionHighlightForeground": "#f00",
  "editorOverviewRuler.warningForeground": theme.yellow,
  "editorOverviewRuler.wordHighlightForeground": "#f00",
  "editorOverviewRuler.wordHighlightStrongForeground": "#f00",
  "editorRuler.foreground": theme.backgroundLight,
  "editorWarning.border": theme.background,
  "editorWarning.foreground": theme.yellow,
  "editorWhitespace.foreground": theme.foregroundAlpha25,
};
