const theme = require("../theme");

// Integrated Terminal Colors
// https://code.visualstudio.com/api/references/theme-color#integrated-terminal-colors

module.exports = {
  "terminal.background": theme.slate,
  "terminal.border": theme.slate[200],
  "terminal.foreground": theme.ash,
  "terminal.ansiBlack": theme.ash[700],
  "terminal.ansiBlue": theme.blue,
  "terminal.ansiBrightBlack": theme.ash[700],
  "terminal.ansiBrightBlue": theme.blue,
  "terminal.ansiBrightCyan": theme.cyan,
  "terminal.ansiBrightGreen": theme.green,
  "terminal.ansiBrightMagenta": theme.magenta,
  "terminal.ansiBrightRed": theme.red,
  "terminal.ansiBrightWhite": theme.ash,
  "terminal.ansiBrightYellow": theme.yellow,
  "terminal.ansiCyan": theme.cyan,
  "terminal.ansiGreen": theme.green,
  "terminal.ansiMagenta": theme.magenta,
  "terminal.ansiRed": theme.red,
  "terminal.ansiWhite": theme.ash,
  "terminal.ansiYellow": theme.yellow,
  "terminal.selectionBackground": theme.ash[50],
  "terminal.selectionForeground": theme.slate,
  "terminal.inactiveSelectionBackground": theme.ash[500][25],
  "terminal.findMatchBackground": theme.yellow,
  "terminal.findMatchBorder": theme.transparent,
  "terminal.findMatchHighlightBackground": theme.yellow,
  "terminal.findMatchHighlightBorder": theme.transparent,
  "terminal.hoverHighlightBackground": theme.ash[500][25],
  "terminal.dropBackground": theme.slate[700][50],
  "terminal.tab.activeBorder": theme.blue,
  "terminalCommandDecoration.defaultBackground": theme.ash[700],
  "terminalCommandDecoration.successBackground": theme.green,
  "terminalCommandDecoration.errorBackground": theme.red,
  "terminalOverviewRuler.cursorForeground": theme.ash,
  "terminalOverviewRuler.findMatchForeground": theme.yellow,
  "terminalOverviewRuler.border": theme.slate[200],
  "terminalStickyScroll.background": theme.slate[700],
  "terminalStickyScroll.border": theme.slate[200],
  "terminalStickyScrollHover.background": theme.slate[400],
  "terminal.initialHintForeground": theme.ash[700],
  "terminalCommandGuide.foreground": theme.ash[700],
  "terminalSymbolIcon.aliasForeground": theme.ash,
  "terminalSymbolIcon.branchForeground": theme.blue,
  "terminalSymbolIcon.commitForeground": theme.green,
  "terminalSymbolIcon.flagForeground": theme.yellow,
  "terminalSymbolIcon.optionForeground": theme.ash,
  "terminalSymbolIcon.optionValueForeground": theme.orange,
  "terminalSymbolIcon.methodForeground": theme.blue,
  "terminalSymbolIcon.argumentForeground": theme.orange,
  "terminalSymbolIcon.inlineSuggestionForeground": theme.cyan,
  "terminalSymbolIcon.fileForeground": theme.ash,
  "terminalSymbolIcon.folderForeground": theme.ash[700],
  "terminalSymbolIcon.pullRequestDoneForeground": theme.green,
  "terminalSymbolIcon.pullRequestForeground": theme.blue,
  "terminalSymbolIcon.remoteForeground": theme.blue,
  "terminalSymbolIcon.stashForeground": theme.yellow,
  "terminalSymbolIcon.symbolText": theme.ash,
  "terminalSymbolIcon.symbolicLinkFileForeground": theme.cyan,
  "terminalSymbolIcon.symbolicLinkFolderForeground": theme.cyan,
  "terminalSymbolIcon.tagForeground": theme.yellow,
  "terminalCursor.background": theme.slate,
  "terminalCursor.foreground": theme.ash,
};
