const theme = require("../theme");

// Status Bar Colors
// https://code.visualstudio.com/api/references/theme-color#status-bar-colors

module.exports = {
  "statusBar.background": theme.slate,
  "statusBar.foreground": theme.ash[700],
  "statusBar.border": theme.slate[500],
  "statusBar.debuggingBackground": theme.slate,
  "statusBar.debuggingForeground": theme.ash,
  "statusBar.debuggingBorder": theme.slate[400],
  "statusBar.noFolderForeground": theme.ash[700],
  "statusBar.noFolderBackground": theme.slate,
  "statusBar.noFolderBorder": theme.slate[500],
  "statusBarItem.activeBackground": theme.slate,
  "statusBarItem.hoverForeground": theme.ash,
  "statusBarItem.hoverBackground": theme.slate[400],
  "statusBarItem.prominentForeground": theme.ash,
  "statusBarItem.prominentBackground": theme.slate[400],
  "statusBarItem.prominentHoverForeground": theme.ash,
  "statusBarItem.prominentHoverBackground": theme.slate[400],
  "statusBarItem.remoteBackground": theme.blue,
  "statusBarItem.remoteForeground": theme.slate,
  "statusBarItem.remoteHoverBackground": theme.blue,
  "statusBarItem.remoteHoverForeground": theme.slate,
  "statusBarItem.errorBackground": theme.red,
  "statusBarItem.errorForeground": theme.slate,
  "statusBarItem.errorHoverBackground": theme.red,
  "statusBarItem.errorHoverForeground": theme.slate,
  "statusBarItem.warningBackground": theme.yellow,
  "statusBarItem.warningForeground": theme.slate,
  "statusBarItem.warningHoverBackground": theme.yellow,
  "statusBarItem.warningHoverForeground": theme.slate,
  "statusBarItem.compactHoverBackground": theme.slate[400],
  "statusBarItem.focusBorder": theme.blue,
  "statusBar.focusBorder": theme.blue,
  "statusBarItem.offlineBackground": theme.ash[700],
  "statusBarItem.offlineForeground": theme.slate,
  "statusBarItem.offlineHoverForeground": theme.ash,
  "statusBarItem.offlineHoverBackground": theme.slate[400],
};
